  general = {
    name = "Audioleaf Pi";
    output_backend = "alsa";
  };

  alsa = {
    output_device = "hw:Loopback,0,0";
    output_rate = 44100;
    output_format = "S16_LE";
    output_channels = 2;
    use_mmap_if_available = "no";
  };

  metadata = {
    enabled = "yes";
    include_cover_art = "yes";
    pipe_name = "/tmp/shairport-sync-metadata";
  };
