  general = {
    name = "Audioleaf Pi";
    output_backend = "alsa";
  };

  alsa = {
    output_device = "default";
  };

  metadata = {
    enabled = "yes";
    include_cover_art = "yes";
    pipe_name = "/tmp/shairport-sync-metadata";
  };
